name: 'Build Repo'
inputs:
  cmake-args:
    required: true
  config:
    required: true
  bin-dir:
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
        WORK_DIR=`pwd`
        cd ../../builds/$REPO_NAME
        python scripts/update_version_string.py Eng.cpp
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ inputs.config }} ${{ inputs.cmake-args }}
        cd ..
        cmake --build build --parallel 16
        if [ -n "${{ inputs.bin-dir }}" ]; then
          mkdir $WORK_DIR/${{ inputs.bin-dir }}
          mkdir $WORK_DIR/${{ inputs.bin-dir }}/test_data
          cp build/tests/test_Eng* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Gui/tests/test_Gui* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Ren/tests/test_Ren* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Ren/SW/tests/test_SW* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Sys/tests/test_Sys* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Phy/tests/test_Phy* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Snd/tests/test_Snd* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Net/tests/test_Net* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/glslx/tests/test_glslx* $WORK_DIR/${{ inputs.bin-dir }}
        fi
      shell: bash
