name: 'Build Repo'
inputs:
  cmake-args:
    required: true
  config:
    required: true
  bin-dir:
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        WORK_DIR=`pwd`
        cd ../../builds/Ren
        python scripts/update_version_string.py Context.cpp
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" ${{ inputs.cmake-args }}
        cd ..
        cmake --build build --target ALL_BUILD --config ${{ inputs.config }} --parallel 16
        if [ -n "${{ inputs.bin-dir }}" ]; then
          mkdir $WORK_DIR/${{ inputs.bin-dir }}
          mkdir $WORK_DIR/${{ inputs.bin-dir }}/test_data
          cp build/tests/${{ inputs.config }}/test_Ren* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/SW/tests/${{ inputs.config }}/test_SW* $WORK_DIR/${{ inputs.bin-dir }}
        fi
      shell: bash
