name: Schedule

on:
  schedule:
    - cron: '0 5 * * *'  # Run every day at 5 o'clock

jobs:
  build-windows-x86_64-dbg:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=OFF"
          config: "Debug"
  build-windows-x86_64-dev:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=OFF"
          config: "RelWithDebInfo"
  # build-windows-x86_64-asan:
  #   runs-on: [ windows, builder ]
  #   steps:
  #     - name: Checkout Workflows
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: .github
  #     - name: Re-initialize repository
  #       uses: ./.github/actions/checkout
  #     - name: Compile the code
  #       uses: ./.github/actions/build-windows
  #       with:
  #         cmake-args: ""
  #         config: "Asan"
  #         bin-dir: "windows-x86_64-asan"
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: windows-x86_64-asan
  #         path: windows-x86_64-asan/
  build-windows-x86_64-clang-rel:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -T ClangCL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
  build-windows-x86_64-clang-dbg:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -T ClangCL"
          config: "Debug"
  build-windows-x86_64-clang-dev:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -T ClangCL"
          config: "RelWithDebInfo"
  build-windows-arm64-dbg:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A ARM64"
          config: "Debug"
  build-windows-arm64-dev:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A ARM64"
          config: "RelWithDebInfo"
  build-linux-x86_64-dbg:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: ""
          config: "Debug"
  build-linux-x86_64-dev:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: ""
          config: "RelWithDebInfo"
  build-macos-universal-dbg:
    runs-on: [ macos, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: '-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"'
          config: "Debug"
  build-macos-universal-dev:
    runs-on: [ macos, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: '-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"'
          config: "RelWithDebInfo"
