name: 'Test'
inputs:
  bin-dir:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        export ASAN_OPTIONS="windows_hook_legacy_allocators=false"
        chmod +x ./${{ inputs.bin-dir }}/test_SW
        chmod +x ./${{ inputs.bin-dir }}/test_Ren-asan
        WORK_DIR=`pwd`
        cd ../../builds/Ren
        $WORK_DIR/${{ inputs.bin-dir }}/test_SW
        $WORK_DIR/${{ inputs.bin-dir }}/test_Ren-asan
      shell: bash
