name: 'Test'
inputs:
  bin-dir:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        export ASAN_OPTIONS="windows_hook_legacy_allocators=false"
        chmod +x ./${{ inputs.bin-dir }}/test_Phy*
        WORK_DIR=`pwd`
        cd ../../builds/Phy
        $WORK_DIR/${{ inputs.bin-dir }}/test_Phy*
      shell: bash
