name: 'Test'
inputs:
  bin-dir:
    required: true
  test-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        export ASAN_OPTIONS="windows_hook_legacy_allocators=false"
        chmod +x ./${{ inputs.bin-dir }}/test_Eng-asan
        WORK_DIR=`pwd`
        cd ../../builds/Eng
        cd $WORK_DIR/${{ inputs.bin-dir }}/test_data
        $WORK_DIR/${{ inputs.bin-dir }}/test_Eng-asan ${{ inputs.test-args }}
        cd ../../..
      shell: bash
