name: 'Build Repo'
inputs:
  cmake-args:
    required: true
  config:
    required: true
  bin-dir:
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
        WORK_DIR=`pwd`
        cd ../../builds/$REPO_NAME
        python scripts/update_version_string.py Eng.cpp
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" ${{ inputs.cmake-args }}
        cd ..
        cmake --build build --target ALL_BUILD --config ${{ inputs.config }} --parallel 16
        if [ -n "${{ inputs.bin-dir }}" ]; then
          mkdir $WORK_DIR/${{ inputs.bin-dir }}
          mkdir $WORK_DIR/${{ inputs.bin-dir }}/test_data
          cp build/tests/${{ inputs.config }}/test_Eng* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Ren/tests/${{ inputs.config }}/test_Ren* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Ren/SW/tests/${{ inputs.config }}/test_SW* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Sys/tests/${{ inputs.config }}/test_Sys* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Phy/tests/${{ inputs.config }}/test_Phy* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Snd/tests/${{ inputs.config }}/test_Snd* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/Net/tests/${{ inputs.config }}/test_Net* $WORK_DIR/${{ inputs.bin-dir }}
          cp build/first-party/glslx/tests/${{ inputs.config }}/test_glslx* $WORK_DIR/${{ inputs.bin-dir }}
        fi
      shell: bash
