name: 'Test'
inputs:
  bin-dir:
    required: true
  test-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        export ASAN_OPTIONS="windows_hook_legacy_allocators=false"
        chmod +x ./${{ inputs.bin-dir }}/test_Eng-tsan
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
        WORK_DIR=`pwd`
        cd ../../builds/$REPO_NAME
        cp $WORK_DIR/${{ inputs.bin-dir }}/*spirv_compiler* $WORK_DIR/../../builds/$REPO_NAME/tests/test_data/ || true
        cd $WORK_DIR/${{ inputs.bin-dir }}/test_data
        $WORK_DIR/${{ inputs.bin-dir }}/test_Eng-tsan ${{ inputs.test-args }}
        cd ../../..
      shell: bash
