name: CI

on:
  push:

jobs:
  build-windows-x86_64-gl-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-gl"
      - name: Prepare assets
        uses: ./.github/actions/prepare-assets
        with:
          bin-dir: "windows-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-gl
          path: windows-x86_64-gl/
  build-windows-x86_64-vk-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-vk"
      - name: Prepare assets
        uses: ./.github/actions/prepare-assets
        with:
          bin-dir: "windows-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-vk
          path: windows-x86_64-vk/
  build-linux-x86_64-gl-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-gl"
      - name: Prepare assets
        uses: ./.github/actions/prepare-assets
        with:
          bin-dir: "linux-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-gl
          path: linux-x86_64-gl/
  build-linux-x86_64-vk-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-vk"
      - name: Prepare assets
        uses: ./.github/actions/prepare-assets
        with:
          bin-dir: "linux-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-vk
          path: linux-x86_64-vk/
  # test-windows-x86_64-gl-nv:
  #   runs-on: [ windows, x86_64, nv ]
  #   needs:
  #     - build-windows-x86_64-gl-rel
  #   steps:
  #     - name: Checkout Workflows
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: .github
  #     - name: Re-initialize repository
  #       uses: ./.github/actions/checkout
  #     - name: Run Tests
  #       uses: ./.github/actions/test
  #       with:
  #         bin-dir: "windows-x86_64-gl-nv"
  #         test-args: "-j2"
  test-windows-x86_64-vk-amd:
    runs-on: [ windows, x86_64, amd ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          test-args: "-j2 --device AMD"
  test-windows-x86_64-vk-nv:
    runs-on: [ windows, x86_64, nv ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          test-args: "-j2 --device NV"
  test-windows-x86_64-vk-arc:
    runs-on: [ windows, x86_64, arc ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          test-args: "-j2 --device Arc"
  test-windows-x86_64-vk-xe:
    runs-on: [ windows, x86_64, xe ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          test-args: "-j2 --device Xe --validation_level 1"
  test-linux-x86_64-vk-amd:
    runs-on: [ linux, x86_64, amd ]
    needs:
      - build-linux-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64-vk"
          test-args: "-j2 --device AMD"
  test-linux-x86_64-vk-nv:
    runs-on: [ linux, x86_64, nv ]
    needs:
      - build-linux-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64-vk"
          test-args: "-j2 --device NV"
