name: CI

on:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 o'clock

jobs:
  build-windows-x86_64-gl-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-gl
          path: windows-x86_64-gl/
  build-windows-x86_64-gl-dbg:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=GL"
          config: "Debug"
  build-windows-x86_64-gl-dev:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=GL"
          config: "RelWithDebInfo"
  build-windows-x86_64-vk-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-vk
          path: windows-x86_64-vk/
  build-windows-x86_64-vk-dbg:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=VK"
          config: "Debug"
  build-windows-x86_64-vk-dev:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=VK"
          config: "RelWithDebInfo"
  build-linux-x86_64-gl-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-gl
          path: linux-x86_64-gl/
  build-linux-x86_64-gl-dbg:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=GL"
          config: "Debug"
  build-linux-x86_64-gl-dev:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=GL"
          config: "RelWithDebInfo"
  build-linux-x86_64-vk-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-vk
          path: linux-x86_64-vk/
  build-linux-x86_64-vk-dbg:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK"
          config: "Debug"
  build-linux-x86_64-vk-dev:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK"
          config: "RelWithDebInfo"
